# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 05:27
from __future__ import unicode_literals

import ckeditor.fields
import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutOurTrousers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('description2', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'О наших брюках',
                'verbose_name_plural': 'О наших брюках',
            },
        ),
        migrations.CreateModel(
            name='CategorySeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('зима', 'Зима'), ('весна', 'Весна'), ('лето', 'Лето'), ('осень', 'Осень')], max_length=255, unique=True, verbose_name='Сезон')),
                ('image', models.ImageField(upload_to='images/jpg', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Категория Сезон',
                'verbose_name_plural': 'Категория Сезоны',
            },
        ),
        migrations.CreateModel(
            name='CategorySize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=255, verbose_name='Размер')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Категория Размер',
                'verbose_name_plural': 'Категория Размеры',
            },
        ),
        migrations.CreateModel(
            name='CategoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Категория Тип',
                'verbose_name_plural': 'Категория Типы',
            },
        ),
        migrations.CreateModel(
            name='OrderOfProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=255, verbose_name='Эл. почта')),
                ('id_product', models.CharField(max_length=255, verbose_name='ID товара')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Итого')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Время заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('description', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('currency', models.CharField(choices=[('KGS', 'сом'), ('RUB', 'рубль')], default='KGS', max_length=255, verbose_name='Валюта')),
                ('fabric_structure', models.CharField(blank=True, max_length=255, null=True, verbose_name='Состав ткани')),
                ('weight_of_1_line', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вес 1 линии')),
                ('in_the_1st_line', models.CharField(blank=True, max_length=255, null=True, verbose_name='В 1-ой линейке')),
                ('action', models.BooleanField(default=False, help_text='Поставьте галочку, если едет акция на этот товар', verbose_name='Акция')),
                ('popular', models.BooleanField(default=False, help_text='Поставьте галочку, если товар популярный', verbose_name='Популярное')),
                ('added_to', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductColors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название цвета')),
                ('color', colorfield.fields.ColorField(default='#ffff00', max_length=18, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет товара',
                'verbose_name_plural': 'Цвета товара',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/png', verbose_name='Картинкa')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='catalog.Product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Картинка Товара',
                'verbose_name_plural': 'Картинки Товара',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(related_name='product_colors', to='catalog.ProductColors', verbose_name='Категория Цвет'),
        ),
        migrations.AddField(
            model_name='product',
            name='create_at',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.ManyToManyField(default='', to='catalog.CategorySeason', verbose_name='Категория Сезон'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(to='catalog.CategorySize', verbose_name='Категория Рамер'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ManyToManyField(to='catalog.CategoryType', verbose_name='Категория Тип'),
        ),
        migrations.AddField(
            model_name='orderofproduct',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.ProductColors', verbose_name='Цвет товара'),
        ),
    ]
