# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 05:27
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('description2', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание 2')),
                ('image', models.ImageField(upload_to='images/jpg', verbose_name='Картинка')),
                ('send_to_subscribers', models.BooleanField(default=False, verbose_name='Отправить подписчикам')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публакации')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='Эл. почта')),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписчики',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Type', verbose_name='Тип'),
        ),
    ]
